language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsfml-dev
  - git clone https://github.com/eclipse/mosquitto.git
  - cd mosquitto
  - cmake .
  - make
  - sudo make -i install #mosquitto is does not install without errors...
  - cd ..

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script: make all
