language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
# - osx

#matrix:
# allow_failures:
#   - os: osx

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsfml-dev libmosquittopp-dev
  -

script: make all
